- name: Installing Apache HTTPD 
  package:
    name: "{{ web_software }}"
    state: present
- name: Installing PHP software
  package:
    name: "{{ server_language }}"
    state: present
- name: Deploying Website 
  copy:
    src: "files/index.php"
    dest: "/var/www/html/index.php"
  notify: "On Content Change"
- name: Starting the service
  service:
    name: "{{ web_service }}"
    state: started





